## Python Libraries-:

1. Numpy
2. Pandas

## Numpy:- 

In [154]:
import numpy as np

#### One Dimensional Array

In [155]:
#List
my_lst = [1,2,3,4,5]
my_lst

[1, 2, 3, 4, 5]

In [156]:
#Array
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)
print(arr)


[1 2 3 4 5]


In [157]:
type(arr)

numpy.ndarray

In [158]:
#1D array is also called as vector. It has only rows.
arr.shape

(5,)

#### Two Dimensional Array

In [159]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [160]:
#2D array has combination of rows and columns.
arr2.shape

(2, 3)

In [161]:
type(arr2)

numpy.ndarray

#### Multi Dimensional Array

In [162]:
List1 = [1,2,3,4,5,6,5,67]
List2 = [2,3,4,6,8,9,12,56]
List3 = [3,4,5,7,8,6,9,23]

In [163]:
arr3 = np.array([List1, List2, List3])

In [164]:
print(arr3)

[[ 1  2  3  4  5  6  5 67]
 [ 2  3  4  6  8  9 12 56]
 [ 3  4  5  7  8  6  9 23]]


## dimension of the matrix must be equal in 2d or multi-demensional. Hence, it will run but give warning and provide incorrect output(basically assume Object(String)).

In [165]:
#Two list with diffrent size
List1 = [1,2,3,4,5,6,5,67,3,5,6]
List2 = [2,3,4,6,8,9,12,56,23,45,5,6,7,8,9,4,23]

In [166]:
arr4 = np.array([List1, List2])

C:\Users\inder\AppData\Local\Temp\ipykernel_16900\2213537179.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array([List1, List2])


In [167]:
print(arr4)

[list([1, 2, 3, 4, 5, 6, 5, 67, 3, 5, 6])
 list([2, 3, 4, 6, 8, 9, 12, 56, 23, 45, 5, 6, 7, 8, 9, 4, 23])]


#### Reshape - It is use to reshape the size of the array.

**Syntax** -:
Array_name.reshape(Row, Column)

In [168]:
List1 = [1,2,3,4,5,6,5,67]
List2 = [2,3,4,6,8,9,12,56]
List3 = [3,4,5,7,8,6,9,23]

In [169]:
arr5 = np.array([List1, List2, List3])

In [170]:
print(arr5)

[[ 1  2  3  4  5  6  5 67]
 [ 2  3  4  6  8  9 12 56]
 [ 3  4  5  7  8  6  9 23]]


In [171]:
arr5.shape

(3, 8)

In [172]:
arr5.reshape(4,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 5, 67,  2,  3,  4,  6],
       [ 8,  9, 12, 56,  3,  4],
       [ 5,  7,  8,  6,  9, 23]])

#### Dimension

To check Dimension of the array

Syntax-:
Array_name.ndim

In [173]:
List1 = [1,2,3,4,5,6,5,67]
List2 = [2,3,4,6,8,9,12,56]
List3 = [3,4,5,7,8,6,9,23]
arr5 = np.array([List1, List2, List3])

In [174]:
arr5.ndim

2

## Indexing-:

1. Indexing starts with Zero.
2. It is basically use to seprate the part of array.
3. It is use to print the array as per requirment

**Syntax** -:
1D-> Array_name[index_Number]

2D-> Array_name[Row_Starts:Row_ends,Column_Starts:Column_ends] 

Multi-Dimensional-> In this case, Systax is same as 2d but index_count will increase on the basis of dimension(Below example). 

In [175]:
arr= np.array([1,2,3,4,45,5,6,6,7,78])

In [176]:
arr[3]

4

In [177]:
#Multi-Dimensional indexing
List1 = [1,2,3,4,5,6,5,67]
List2 = [2,3,4,6,8,9,12,56]
List3 = [3,4,5,7,8,6,9,23]

In [178]:
arr6 = np.array([List1,List2,List3])

In [179]:
print(arr6)

[[ 1  2  3  4  5  6  5 67]
 [ 2  3  4  6  8  9 12 56]
 [ 3  4  5  7  8  6  9 23]]


In [180]:
arr6.ndim

2

In [181]:
print(arr6[:2,:2])

[[1 2]
 [2 3]]


In [182]:
arr6 = np.array([[List1,List2,List3]])

In [183]:
arr6.ndim

3

In [184]:
arr6[:]

array([[[ 1,  2,  3,  4,  5,  6,  5, 67],
        [ 2,  3,  4,  6,  8,  9, 12, 56],
        [ 3,  4,  5,  7,  8,  6,  9, 23]]])

In [185]:
#3-Dimension
print(arr6[:2,:2,:4])

[[[1 2 3 4]
  [2 3 4 6]]]


### Arange-:

It is very useful function it will create array as per your requiremnt.
It behaves like range function where you give the input it will create array.
It has the feature of step.

**Syntax** -:
Array_name = np.arange(Start, stop, step)

In [186]:
arr7 = np.arange(0,10,2)

In [187]:
arr7

array([0, 2, 4, 6, 8])

In [188]:
arr8 = np.arange(start= 10,stop = 101,step=10)

In [189]:
arr8

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### Linspace

It will create array with equal diffrences as per number. 
It hasn't the feature of step.

**Syntax** -:
array_name = np.linspace(start,stop,numbers)

In [190]:
arr9=np.linspace(1,10,10)

In [191]:
arr9

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [192]:
arr9=np.linspace(start= 1,stop=10,num=20)

In [193]:
print(arr9)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### Copy Function
Copy function -: Copy function use when we dont want any changes in our original dataset.If we dont use copy function then it will update original list.

**Syntax** -:
Array_name.copy()

In [194]:
# Without Copy Method
List1 = [1,2,3,4,5,6,5,67]
List2 = [2,3,4,6,8,9,12,56]
List3 = [3,4,5,7,8,6,9,23]

In [195]:
arr10= np.array([List1,List2,List3])

In [196]:
arr10[1:]=100

In [197]:
print(arr10)

[[  1   2   3   4   5   6   5  67]
 [100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100]]


In [198]:
# Using Copy Method
List1 = [1,2,3,4,5,6,5,67]
List2 = [2,3,4,6,8,9,12,56]
List3 = [3,4,5,7,8,6,9,23]

In [199]:
arr11= np.array([List1,List2,List3])

In [200]:
arr_11=arr11.copy()

In [201]:
arr11[1:]=5000

In [202]:
arr11

array([[   1,    2,    3,    4,    5,    6,    5,   67],
       [5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000],
       [5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000]])

In [203]:
arr_11

array([[ 1,  2,  3,  4,  5,  6,  5, 67],
       [ 2,  3,  4,  6,  8,  9, 12, 56],
       [ 3,  4,  5,  7,  8,  6,  9, 23]])

### Broadcasting

Broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

**Matrix** = 

+, - , *, / -> Length of both matrix should be same

If any of the array is 2D or Multi-dimensional then output is also in that dimensional


In [204]:
List1 = [1,2,3,4,5,6,5,67]
List2 = [2,3,4,6,8,9,12,56]
List3 = [3,4,5,7,8,6,9,23]

In [205]:
arr11= np.array([List1,List2,List3])

In [206]:
arr11.shape

(3, 8)

In [207]:
arr12= np.array([2,3,5,2,3,4,5,6])

In [208]:
print(arr12)

[2 3 5 2 3 4 5 6]


In [209]:
arr12.shape

(8,)

In [210]:
arr11*arr12

array([[  2,   6,  15,   8,  15,  24,  25, 402],
       [  4,   9,  20,  12,  24,  36,  60, 336],
       [  6,  12,  25,  14,  24,  24,  45, 138]])

In [211]:
arr11

array([[ 1,  2,  3,  4,  5,  6,  5, 67],
       [ 2,  3,  4,  6,  8,  9, 12, 56],
       [ 3,  4,  5,  7,  8,  6,  9, 23]])

In [212]:
arr11+arr12

array([[ 3,  5,  8,  6,  8, 10, 10, 73],
       [ 4,  6,  9,  8, 11, 13, 17, 62],
       [ 5,  7, 10,  9, 11, 10, 14, 29]])

In [213]:
arr11-arr12

array([[-1, -1, -2,  2,  2,  2,  0, 61],
       [ 0,  0, -1,  4,  5,  5,  7, 50],
       [ 1,  1,  0,  5,  5,  2,  4, 17]])

In [214]:
arr11/arr12

array([[ 0.5       ,  0.66666667,  0.6       ,  2.        ,  1.66666667,
         1.5       ,  1.        , 11.16666667],
       [ 1.        ,  1.        ,  0.8       ,  3.        ,  2.66666667,
         2.25      ,  2.4       ,  9.33333333],
       [ 1.5       ,  1.33333333,  1.        ,  3.5       ,  2.66666667,
         1.5       ,  1.8       ,  3.83333333]])

In [215]:
# Matrix

N = [1,2,3]
M = [3,5,6]
Arr_N = np.array(N)
Arr_M = np.array([M])

In [216]:
Arr_N -Arr_M

array([[-2, -3, -3]])

In [217]:
Arr_N *Arr_M

array([[ 3, 10, 18]])

In [218]:
Arr_N +Arr_M

array([[4, 7, 9]])

In [219]:
Arr_N /Arr_M

array([[0.33333333, 0.4       , 0.5       ]])

## Some useful Function

### If we want to print array with condition

**Syntax** -:
Array_name = [Array_name,operator,operands]

In [220]:
List2 = [2,3,4,6,8,9,12,56,50,23,4,5,4,2,12,1,21,11,234,456,43,456]

In [221]:
arr_2 = np.array([List2])

In [222]:
#More than 2
arr_2[arr_2>2]

array([  3,   4,   6,   8,   9,  12,  56,  50,  23,   4,   5,   4,  12,
        21,  11, 234, 456,  43, 456])

### Creating Array with ones 

**Syntax** -:
np.ones(Shape, dtype= Data_type(int/Float))

In [223]:
np.ones(54,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [224]:
np.ones(54,dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

# Statring with Random

### Random array 

It helps to create array with random data. It changes everytime, we run.

**Syntax** -:
np.random.rand(row,column)


In [225]:
np.random.rand(3,3)

array([[0.50667136, 0.08977469, 0.03958304],
       [0.73473858, 0.59043022, 0.58117239],
       [0.02129043, 0.48767576, 0.63403554]])

### Randn- Standard normal Distribution

The random.randn() is a numpy library function that returns an array of random samples from the standard normal distribution. It allows specified dimensions as an argument and returns an array of specified dimensions.

**Syntax** -:
np.random.randn(Rows,Columns)

In [226]:
np.random.randn(2,2)

array([[-0.37567485,  0.60600455],
       [ 1.18302965,  1.302944  ]])

## Randint

It helps to generate random integer number under the range on the basis of parameters.It changes everytime we run.

**Syntax** -:

np.random.randint(Start,Stop,Array Element).reshape(row,column)

(Array Element=Row* Column)


In [227]:
np.random.randint(0,100,12).reshape(4,3)

array([[75, 61, 90],
       [32, 10, 81],
       [52, 46, 31],
       [45, 62, 79]])

## random sample-:

Random_sample() method, we can sample the data values and choose random data fat ease. It selects random samples between 
[0.0 – 1.0] only

**Syntax** -:
np.random.random_sample(row,column)

In [228]:
np.random.random_sample((2,5))

array([[0.26863626, 0.37004621, 0.24977566, 0.9597903 , 0.9437124 ],
       [0.74279133, 0.7037546 , 0.76625668, 0.24063927, 0.86694144]])

# Pandas

In [229]:
import pandas as pd

## Data Frame - More than one Column/Row
## Data Series- Only one Column and one Row

#### Creating Data Frame with an array(arange function) 

Syntax -:

pd.DataFrame(np.arange(Row,Columns).reshape(row,column),index=[Rows_name(count(Reshape(rows)), columns = [Coluns_name(count(Reshape(Columns))

In [230]:


df = pd.DataFrame(np.arange(0,20).reshape(5,4),index =['Row1','Row2','Row3','Row4','Row5'],
                  columns = ['Col1','Col2','Col3','Col4'])

In [231]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

### Creating data into CSV file

In [232]:
df.to_csv('Test.csv')

## Accessing the Element 

1. Loc(Location) - It provides the rows and columns of specific location.
Syntax -:

df.loc['index_number', Column_name]

2. iloc(Index Location)-It provides the rows and columns of specific index.
Syntax -:

df.iloc[StartRow:EndRow,StartColumn:EndColumn]


In [233]:
df.loc['Row1']

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int32

### if we want to call more than 1 Row then we have to change the dimension from 1-D to 2-D.
#### If we call more than one row/Column then we have to call the condition under 2-D array.


In [234]:
df.loc[['Row1','Row2', 'Row3']]

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11

In [235]:
df.loc['Row1','Col1']

0

In [236]:
df.iloc[0:2,0:3]

Col1  Col2  Col3
Row1     0     1     2
Row2     4     5     6

### Converting Data Frame into Array 

In [237]:
print(df.iloc[:,:1].values)

[[ 0]
 [ 4]
 [ 8]
 [12]
 [16]]


###  To Check null value in Data

In [238]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

## Categorical-: This Function will help to identify unique Categories present 

In [239]:
df['Col1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: Col1, dtype: int64

## Unique Value Present

In [240]:
df['Col1'].unique()

array([ 0,  4,  8, 12, 16])

## Calling Specific Row/Column 

In [241]:
#If we call more than one row/Column then we have to call the condition under 2-D array
df[['Col1','Col2']]

Col1  Col2
Row1     0     1
Row2     4     5
Row3     8     9
Row4    12    13
Row5    16    17

## Reading CSV files 

In [242]:
df = pd.read_csv('Test.csv')

In [243]:
df.head()

Unnamed: 0  Col1  Col2  Col3  Col4
0       Row1     0     1     2     3
1       Row2     4     5     6     7
2       Row3     8     9    10    11
3       Row4    12    13    14    15
4       Row5    16    17    18    19

## informaton of the data 

In [244]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  5 non-null      object
 1   Col1        5 non-null      int64 
 2   Col2        5 non-null      int64 
 3   Col3        5 non-null      int64 
 4   Col4        5 non-null      int64 
dtypes: int64(4), object(1)
memory usage: 328.0+ bytes


## Describe the data 

df.describe()- Only include integer/float type 

df.describe(include='all') - include integer/float and categorical 

In [245]:
df.describe(include = 'all')

Unnamed: 0       Col1       Col2       Col3       Col4
count           5   5.000000   5.000000   5.000000   5.000000
unique          5        NaN        NaN        NaN        NaN
top          Row1        NaN        NaN        NaN        NaN
freq            1        NaN        NaN        NaN        NaN
mean          NaN   8.000000   9.000000  10.000000  11.000000
std           NaN   6.324555   6.324555   6.324555   6.324555
min           NaN   0.000000   1.000000   2.000000   3.000000
25%           NaN   4.000000   5.000000   6.000000   7.000000
50%           NaN   8.000000   9.000000  10.000000  11.000000
75%           NaN  12.000000  13.000000  14.000000  15.000000
max           NaN  16.000000  17.000000  18.000000  19.000000

## Displaying data with condition 

In [246]:
df[df['Col1']>8]

Unnamed: 0  Col1  Col2  Col3  Col4
3       Row4    12    13    14    15
4       Row5    16    17    18    19

## StringIO - It understands the data and create rows and column accordingly. 

If we have a data in string

In [247]:
from io import StringIO,BytesIO

In [248]:
data = ('Col1,Col2,Col3\n'
       'x,y,1\n'
       'a,b,2')

In [249]:
type(data)

str

In [250]:
# Can't read the file 
#pd.read_csv(data)

In [251]:
#In memory file format object
StringIO(data)

In [252]:
pd.read_csv(StringIO(data))

Col1 Col2  Col3
0    x    y     1
1    a    b     2

### Reading Specific Column 

In [253]:
df = pd.read_csv(StringIO(data),usecols=['Col1','Col3'])

In [254]:
df

Col1  Col3
0    x     1
1    a     2

## Specifing columns with fixed data-type 

In [255]:
data = ('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '98,23,45')

In [256]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
98,23,45


In [257]:
type(data)

str

In [258]:
df = pd.read_csv(StringIO(data), dtype=object)

In [259]:
df

a   b   c    d
0   1   2   3    4
1   5   6   7    8
2  98  23  45  NaN

In [260]:
df['a']

0     1
1     5
2    98
Name: a, dtype: object

In [261]:
type(df)

pandas.core.frame.DataFrame

## Specifing Data-type respect to each column

In [262]:
df=pd.read_csv(StringIO(data),dtype={'b':int,'c':float,'a':str})

In [263]:
df

a   b     c    d
0   1   2   3.0  4.0
1   5   6   7.0  8.0
2  98  23  45.0  NaN

In [264]:
df['a'][1]

'5'

In [265]:
df['b'][1].dtype

dtype('int32')

In [266]:
df['c'][1].dtype

dtype('float64')

In [267]:
df.dtypes

a     object
b      int32
c    float64
d    float64
dtype: object

### Create index-col 

In [268]:
pd.read_csv(StringIO(data), index_col =0)

b   c    d
a              
1    2   3  4.0
5    6   7  8.0
98  23  45  NaN

### Change in Index Column automatically

In [269]:
data = ('a,b,c,d\n'
       '1,2,3,4,\n'
       '5,6,7,8,\n'
       '98,23,45,')

In [270]:
## By Default index_col is True-: Index Columns create
pd.read_csv(StringIO(data))

a   b    c   d
1    2   3  4.0 NaN
5    6   7  8.0 NaN
98  23  45  NaN NaN

### Change in Index Column

In [271]:
# By Default index_col is False -: default Index Columns 
pd.read_csv(StringIO(data),index_col = False)

a   b   c    d
0   1   2   3  4.0
1   5   6   7  8.0
2  98  23  45  NaN

### Combination Usecols and index_col 

In [272]:
data = ('a,b,c\n'
       '4,apple,bat,\n'
       '8,orange,cow,')

In [273]:
pd.read_csv(StringIO(data),usecols=['a','b','c'],index_col = False)

a       b    c
0  4   apple  bat
1  8  orange  cow

In [274]:
pd.read_csv(StringIO(data))

a    b   c
4   apple  bat NaN
8  orange  cow NaN

### Quoting and Escape characters [Use Full in NLP]

In [275]:
data ='a,b\n"Hello, \\"Bob\\","nice to see you",5'

In [276]:
pd.read_csv(StringIO(data), escapechar='\\')

a  b
0  Hello, "Bob",nice to see you"  5

In [277]:
data ='a,b,c\n"Hello, \\"Bob\\"", "nice to see you",5'

In [278]:
pd.read_csv(StringIO(data), escapechar='\\')

a                   b  c
0  Hello, "Bob"   "nice to see you"  5

## URL to CSV

In [279]:
df = pd.read_csv('https://download.bls.gov/pub/time.series/ap/ap.area',sep='\t')

In [280]:
df.head()

area_code          area_name
0      0000  U.S. city average
1      0100          Northeast
2      0110        New England
3      0120    Middle Atlantic
4      0200            Midwest

## Read Json to CSV 

{Key:Value} -> Key Value Pair

In [281]:
Data = '{"employe_name":"James","Email":"James@gmail.com","Job-profile":[{"title1":"Team Lead","Title2":"SeniorDevloper"}]}'

In [282]:
pd.read_json(Data)

employe_name            Email  \
0        James  James@gmail.com   

                                         Job-profile  
0  {'title1': 'Team Lead', 'Title2': 'SeniorDevlo...

### Read Json from Website 

In [283]:
df= pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header=None)

In [284]:
df

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

## Convert JSON to CSV 

In [285]:
df.to_csv('wine.csv')

## Convert JSON to different Json Format 

In [286]:
df.to_json(orient="records")

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"

## Reading HTML content

In [287]:
url = 'https://en.wikipedia.org/wiki/Python_(programming_language)'

In [288]:
dfs=pd.read_html(url)

In [289]:
dfs[0]

0  \
0                                                 NaN   
1                                                 NaN   
2                                            Paradigm   
3                                         Designed by   
4                                           Developer   
5                                      First appeared   
6                                                 NaN   
7                                      Stable release   
8                                     Preview release   
9                                   Typing discipline   
10                                                 OS   
11                                            License   
12                                Filename extensions   
13                                            Website   
14                              Major implementations   
15  CPython, PyPy, Stackless Python, MicroPython, ...   
16                                           Dialects   
17                      Cython, RPython, Starlark[12]   
18                                      Influenced by   
19  ABC,[13] Ada,[14] ALGOL 68,[15] APL,[16] C,[17...   
20                                         Influenced   
21  Apache Groovy, Boo, Cobra, CoffeeScript,[25] D...   
22                    Python Programming at Wikibooks   

                                                    1  
0                                                 NaN  
1                                                 NaN  
2   Multi-paradigm: object-oriented,[1] procedural...  
3                                    Guido van Rossum  
4                          Python Software Foundation  
5                   20 February 1991; 31 years ago[2]  
6                                                 NaN  
7            3.11.0[3] / 24 October 2022; 18 days ago  
8          3.12.0a1[4] / 25 October 2022; 17 days ago  
9   Duck, dynamic, strong typing;[5] gradual (sinc...  
10  Windows, macOS, Linux/UNIX, Android[7][8] and ...  
11                 Python Software Foundation License  
12  .py, .pyi, .pyc, .pyd, .pyw, .pyz (since 3.5),...  
13                                         python.org  
14                              Major implementations  
15  CPython, PyPy, Stackless Python, MicroPython, ...  
16                                           Dialects  
17                      Cython, RPython, Starlark[12]  
18                                      Influenced by  
19  ABC,[13] Ada,[14] ALGOL 68,[15] APL,[16] C,[17...  
20                                         Influenced  
21  Apache Groovy, Boo, Cobra, CoffeeScript,[25] D...  
22                    Python Programming at Wikibooks

In [290]:
url_mrc = 'https://en.wikipedia.org/wiki/mobile_country_code'

In [291]:
dfs1 = pd.read_html(url_mrc,match='Country', header=0)

In [292]:
dfs1[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

## Reading Excel File 

In [293]:
df_excel = pd.read_excel('sales Target Dashboard.xlsx')

In [294]:
df_excel.head()

S/N       Date  Branch    Pizza Type  Quantity      Time     Time Range  \
0    1 2015-12-11   Abuja       Meatzaa         5  08:00:01  Before 9:00am   
1    2 2015-12-14  Ibadan  Extravaganza         4  08:00:02  Before 9:00am   
2    3 2015-12-04   Ikoyi   BBQ Chicken         5  08:00:04  Before 9:00am   
3    4 2015-12-14  Ibadan  Extravaganza         1  08:00:07  Before 9:00am   
4    5 2015-12-07   Lekki       Meatzaa         4  08:00:08  Before 9:00am   

   Price  Revenue         Manager Location    Weekday  
0      8       40  Christy  Olson    india 1900-01-06  
1      8       32   Dan  Peterson    india 1900-01-02  
2     16       80  Mable  Lindsey    india 1900-01-06  
3      8        8   Dan  Peterson    india 1900-01-02  
4      8       32      Kyle  Carr    india 1900-01-02

## Pickling

All Pandas objects are equipped with to-pickle methods which use python's pickle module to save data structure to disk using the pickle format

In [295]:
df_excel.to_pickle('df_excel')

In [296]:
df=pd.read_pickle('df_excel')

In [297]:
df.head()

S/N       Date  Branch    Pizza Type  Quantity      Time     Time Range  \
0    1 2015-12-11   Abuja       Meatzaa         5  08:00:01  Before 9:00am   
1    2 2015-12-14  Ibadan  Extravaganza         4  08:00:02  Before 9:00am   
2    3 2015-12-04   Ikoyi   BBQ Chicken         5  08:00:04  Before 9:00am   
3    4 2015-12-14  Ibadan  Extravaganza         1  08:00:07  Before 9:00am   
4    5 2015-12-07   Lekki       Meatzaa         4  08:00:08  Before 9:00am   

   Price  Revenue         Manager Location    Weekday  
0      8       40  Christy  Olson    india 1900-01-06  
1      8       32   Dan  Peterson    india 1900-01-02  
2     16       80  Mable  Lindsey    india 1900-01-06  
3      8        8   Dan  Peterson    india 1900-01-02  
4      8       32      Kyle  Carr    india 1900-01-02

In [315]:
from bs4 import BeautifulSoup
mech = Browser
url = "http://www.india.gov.in/topics/health-family-welfare/health"
page = mech.open(url)

soup = BeautifulSoup(page)
for item in soup.select('div.view-content ol li'):
    print('item')

NameError: name 'Browser' is not defined